export const SUPPORTED_NETWORKS = [
    {
      name: "goerli",
      network: "test network",
      chain_id: 5,
      network_id: 5,
      rpc_url: "https://rpc.goerli.mudit.blog/",
      native_currency: {
            symbol: "ETH",
            name: "Ethereum",
            decimals: "18",
            contractAddress: "",
            balance: "",
          },
    },
    // {
    //   name: "Moonbeam",
    //   short_name: "moonbeam",
    //   chain: "Moonbeam",
    //   network: "mainnet",
    //   chain_id: 1284,
    //   network_id: 1284,
    //   rpc_url: "https://rpc.api.moonbeam.network",
    //   native_currency: {
    //     symbol: "GLMR",
    //     name: "Glimmer",
    //     decimals: "18",
    //     contractAddress: "",
    //     balance: "",
    //   },
    // },
    // {
    //   name: "Moonriver",
    //   short_name: "moonriver",
    //   chain: "Moonriver",
    //   network: "mainnet",
    //   chain_id: 1285,
    //   network_id: 1285,
    //   rpc_url: "https://rpc.moonriver.moonbeam.network",
    //   native_currency: {
    //     symbol: "MOVR",
    //     name: "Moonriver",
    //     decimals: "18",
    //     contractAddress: "",
    //     balance: "",
    //   },
    // },
  ]